<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RollForward>Major</RollForward>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>Hereticide</AssemblyName>
    <RootNamespace>Hereticide</RootNamespace>
    <ApplicationIcon></ApplicationIcon>
    <!-- We generate all art in code, so no Content pipeline is needed. -->
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MonoGame.Framework.DesktopGL" Version="3.8.*" />
  </ItemGroup>

</Project>
